# Generated by `mix argus.pins`; do not edit. What each built-in analysis
# reads, resolved from Souffle's transformed program. A change here is a
# change in the unit of incremental work: review the diff.
[
  blocking:
    ~w(async_cast call_arg call_arg_forward call_edge call_site call_site_target call_tag callback_tag catch_tag catch_total clause_call dynamic_call fun_handed_to fun_ref function_def global_op handle_continue_clause implements_behaviour infinity_arg init_continues_to named_pid named_process process_call process_start recv_pattern recv_start remote_call rpc_call rpc_target rpc_timeout_param self_call server_process statem_event_clause sync_call sync_call_site sync_call_timeout timer_arm try_call),
  coupling:
    ~w(async_cast call_arg call_arg_forward call_edge call_site call_site_target call_tag callback_tag child_spec_restart dynamic_call dynamic_child fun_handed_to fun_ref function_def implements_behaviour matches_down monitor_call name_lookup named_pid pid_call pid_signal prior_talks_to_process private_process process_call process_link process_signal process_start server_process sup_call supervisor supervisor_child supervisor_child_name supervisor_site sync_call sync_call_site),
  coverage:
    ~w(async_cast call_arg call_arg_forward dynamic_child ets_new ets_op function_def implements_behaviour imprecision named_pid named_process process_call server_process supervisor supervisor_child sync_call),
  effects:
    ~w(call_edge call_site closure_def dynamic_call ets_new ets_op implements_behaviour impure_call port_open process_register protocol_dispatch pure_contract recv_start remote_call resolved_apply send_msg spawn_call unknown_call),
  ets:
    ~w(call_arg call_arg_forward call_edge catch_tag catch_total closure_def dynamic_child ets_new ets_op ets_op_param ets_option function_def implements_behaviour statem_event_clause supervisor_child try_start),
  exposure:
    ~w(function_def inspect_derived inspect_shows prior_sensitive redacted_field schema_field tls_connect tls_verification),
  failure:
    ~w(bare_rescue call_edge call_followed_by_branch call_result call_site catch_class catch_falls_through catch_tag catch_total closure_def dynamic_call exit_call fun_handed_to fun_ref function_def ignored_error_result implements_behaviour instance macro_generated name_lookup pid_signal private_process process_signal process_start remote_call rpc_call rpc_result spawn_call spec_return supervised_process supervisor_child supervisor_site tail_call try_call try_covers try_covers_closure),
  mailbox:
    ~w(async_cast call_arg call_arg_field call_arg_forward call_edge call_site call_site_target call_tag callback_drops callback_drops_from callback_open callback_ref_head callback_return callback_tag callback_total cancel_clause closure_def demonitor_call dynamic_call fun_handed_to fun_ref function_def implements_behaviour instance macro_generated mailbox_writer matches_down monitor_call monitor_ref_dropped pid_send process_call process_start recv_pattern recv_start remote_call returns_call server_process statem_call_unreplied statem_event_catchall statem_event_clause statem_info_catchall statem_info_open statem_info_tag statem_module statem_state statem_timeout sync_call sync_call_timeout tail_call timer_arm timer_cancel timer_ref timer_store trap_exit),
  races:
    ~w(call_arg call_arg_depends call_arg_element call_arg_field call_arg_forward call_arg_reads call_arg_tuple call_decided call_edge call_site catch_tag catch_total closure_def creating_op dynamic_call dynamic_child effect_decided ets_call_arg ets_effect_order ets_key ets_new ets_op ets_op_param ets_option ets_table_path ets_tid_arg ets_value field_compared field_decides fun_handed fun_handed_to fun_ref function_def global_op implements_behaviour impure_call local_call mnesia_op name_lookup name_release process_start remote_call resolved_apply returns_call returns_depends site_depends site_reads source_table spec_return start_error_compared statem_event_clause table_alloc table_use try_covers try_start),
  shutdown:
    ~w(async_cast call_arg call_arg_forward call_edge call_site call_site_target call_tag callback_stop_reason callback_tag callback_total catch_total catch_tuple_tag demonitor_call dynamic_call dynamic_child fun_handed fun_handed_to fun_ref function_def implements_behaviour impure_call monitor_call pid_arg private_process process_call process_start remote_call resolved_apply server_process skipped_on_shutdown source_process statem_event_clause statem_state sup_call supervisor supervisor_child supervisor_child_name supervisor_site sync_call sync_call_site trap_exit try_covers unknown_call),
  startup:
    ~w(async_cast call_arg call_arg_forward call_edge call_site call_site_target call_tag callback_tag callback_timeout clause_call conditional_call distributed_store_op dynamic_call dynamic_child fun_handed_to fun_ref function_def global_op global_register handle_continue_clause ignored_error_result implements_behaviour impure_call init_continues_to mailbox_writer node_operation post_start_call process_call process_start recv_start remote_call rpc_call server_process statem_timeout sup_call supervisor supervisor_child supervisor_site sync_call sync_call_site try_start unconditional_call_edge),
  state_machine: ~w(statem_initial statem_module statem_state statem_transition),
  structure:
    ~w(function_def global_register implements_behaviour process_register supervisor_child supervisor_child_form supervisor_site),
  unsafe_input:
    ~w(call_arg_derived call_edge code_execution dynamic_child function_def http_route implements_behaviour prior_reads sink_arg_derived socket_transport supervisor_max_children unsafe_atom_creation unsafe_deserialization)
]
