defmodule Mix.Tasks.Argus.Pins do
  @shortdoc "Rewrites the per-analysis input pins from what Souffle reads"

  @moduledoc """
  Writes `test/argus/analysis_inputs.exs`: for every built-in analysis,
  the relations Souffle's transformed program actually reads.

      mix argus.pins           # rewrite the pins
      mix argus.pins --check   # exit 1 if they differ from the current program

  The pins are the unit of incremental work — a consumer re-solves an
  analysis when any relation in its set changes — so a widening is a
  latency regression and a narrowing is the point of a change; either
  belongs in a diff. `Argus.DlDeclarationsTest` fails until the file is
  regenerated, and the diff of that file is the review.
  """

  use Mix.Task

  alias Argus.Analysis

  @target Path.join(["test", "argus", "analysis_inputs.exs"])

  @impl Mix.Task
  def run(args) do
    {opts, _, _} = OptionParser.parse(args, strict: [check: :boolean])
    Mix.Task.run("app.config")

    inputs = current()

    cond do
      Keyword.get(opts, :check, false) and pinned() == inputs ->
        Mix.shell().info("#{@target} is current")

      Keyword.get(opts, :check, false) ->
        Mix.raise("#{@target} is stale — run `mix argus.pins` and commit the result")

      true ->
        File.write!(@target, render(inputs))
        Mix.Task.run("format", [@target])
        Mix.shell().info("wrote #{@target}")
    end
  end

  # Compared as data, not text: `mix format` may rewrap the file.
  defp pinned do
    @target
    |> Code.eval_file()
    |> elem(0)
    |> Map.new(fn {name, rels} -> {name, Enum.sort(rels)} end)
  end

  @doc "The input set of every built-in analysis, as Souffle reports it."
  @spec current() :: %{atom() => [String.t()]}
  def current do
    for mod <- Analysis.builtin_analysis_modules(), into: %{} do
      name = mod.name()

      case Analysis.input_relations(name) do
        {:ok, relations} -> {name, Enum.sort(relations)}
        {:error, why} -> Mix.raise("could not resolve inputs of #{name}: #{inspect(why)}")
      end
    end
  end

  @doc "The pins file's text for an input map."
  @spec render(%{atom() => [String.t()]}) :: String.t()
  def render(inputs) do
    body =
      inputs
      |> Enum.sort()
      |> Enum.map_join(",\n", fn {name, relations} ->
        "  #{name}: ~w(#{Enum.join(relations, " ")})"
      end)

    """
    # Generated by `mix argus.pins`; do not edit. What each built-in analysis
    # reads, resolved from Souffle's transformed program. A change here is a
    # change in the unit of incremental work: review the diff.
    [
    #{body}
    ]
    """
  end
end
